### PR TITLE
Fix graph not showing first time, add obj_ea to var and obj op types

### PR DESCRIPTION
**Pull request by stevemk14ebr**
Thanks for your awesome plugin!

Here is a patch that fixes the graph sometimes not being visible when it first shows up. This can be fixed manually by clicking 'fit window' in the graph view, I do that programmatically here. I've also added output to show the obj_ea to var and obj types as this is sometimes useful to know during dev.

### CODE REVIEW

**Review by patois — CHANGES_REQUESTED** [review]
Thank you for your pull request, I am glad you're finding the plugin useful!
I would suggest the following changes for lines 170 and 171, since the cot_var type does not have a valid obj_ea member:
```
            if op == ida_hexrays.cot_obj:
                parts.append("obj_ea: %x" % item.obj_ea)
```

If you would also remove the change on line 112 please, since it does not address the same erroneous behavior if a new function is decompiled without closing the current viewer.
I have just implemented a proper fix that addresses this problem "globally" and also fixes a bug that your pull request helped me locate.
Thanks!

**Comment by stevemk14ebr** [comment]
Done! Curious to see how you fixed the graph display issue

**Review by patois — APPROVED** [review]

**Comment by patois** [comment]
So I've decided to center the graph on the root note by default as opposed to fit the viewer since I think that is what the "graph overview" is meant for. If using the plugin on a smaller screen, fitting the viewer will make the graph become pretty unreadable on huge functions, so it'd require additional clicks/keyboard shortcuts in order to zoom in to 100%.
I'm hoping this is a desirable fix that can be worked with?! :)

**Comment by stevemk14ebr** [comment]
This works great, thanks!

**Pull request merged**
